### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by emig** [eHealthAfrica/couchdb-ddoc-test#2]
Hi,  isn't couchapp-test a better name?

**Comment by rmehner** [comment]
I have no idea how to properly test for this, given the number of repositories we have, but next time we're renaming, we somehow should make sure, that we don't break the apps which depend on that module or at least leave the old repository as a fallback until everyone upgraded :)

**Comment by jo** [comment]
@rmehner Github keeps a redirect: https://github.com/eHealthAfrica/couchdb-test so this won't break anything until we create a new repository with the old name.
